### ISSUE TITLE
Using bundle editor without placement

### ISSUE THREAD

**Issue by adam-stokes** [Ubuntu-Solutions-Engineering/bundle-placement#16]
A few areas that need to be addressed:

The updated bundle doesn't include multiple units, for example, i have a bundle that has a `compute-slave` and it says (0 of 3 placed). If I hit deploy only one of those units is deployed.

Assignments should go away

(0 of x) should go away

**Comment by mikemccracken** [comment]
fixed the display related issues in https://github.com/Ubuntu-Solutions-Engineering/bundle-placement/commit/d5a7c718943662d703839e5148ea965a348f861c

**Comment by mikemccracken** [comment]
and the num_units issue is fixed here: https://github.com/Ubuntu-Solutions-Engineering/bundle-placement/commit/2b8e3f093208f6786ae7203573af0932ae47b4d3
